"""create initial tables

Revision ID: c564d9f0aefc
Revises: 
Create Date: 2026-09-09 15:53:40.253271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c564d9f0aefc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traders_email'), 'traders', ['email'], unique=True)
    op.create_table('backtests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trader_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(), nullable=False),
    sa.Column('lot_size', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('account_size', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backtest_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('result', sa.Enum('TP', 'SL', name='resulttype'), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pips_ticks', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backtest_entries')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_traders_email'), table_name='traders')
    op.drop_table('traders')
    # ### end Alembic commands ###
